(function() {
  function toggleP(id) { const pr=PRAYERS.find(x=>x.id===id); if(!pr) return; const l=tlog(); const w=!!l.p[id]; const oldLv=S.lv; l.p[id]=!w; let xp=pr.xp; if(isFri()&&id==='dhuhr'&&pr.fri) xp=pr.fri.xp; if(S.ab&&S.ab.exp>=today()) xp*=2; if(!w){ S.tp++; S.xp+=xp; if(isFri()&&id==='dhuhr') S.tj=(S.tj||0)+1; playSound('pop'); if(typeof checkSurpriseReward==='function') checkSurpriseReward('prayer'); } else { S.tp=Math.max(0,S.tp-1); S.xp=Math.max(0,S.xp-xp); if(isFri()&&id==='dhuhr') S.tj=Math.max(0,(S.tj||0)-1); } S.lv=lvFrom(S.xp); checkLevelUp(oldLv); recalc(); checkQ(); checkA(); saveState(); markDirty('today'); markDirty('topbar'); markDirty('lv'); markDirty('progress'); renderDynamic(); if(typeof checkCombo==='function'){const prayedFajr=!!l.p.fajr;const prayedAll=Object.values(l.p||{}).filter(v=>v).length>=5;if(prayedFajr)checkCombo('fajr',true);if(prayedAll)checkCombo('adhkar',true);} if (typeof window.autoTrackJourneyProgress === 'function') window.autoTrackJourneyProgress(); }
  function toggleV(id) { const vp=VOLUNTARY.find(x=>x.id===id); if(!vp) return; const l=tlog(); if(!l.v) l.v={}; const w=!!l.v[id]; const oldLv=S.lv; l.v[id]=!w; let xp=vp.xp; if(S.ab&&S.ab.exp>=today()) xp*=2; if(!w){ S.vc[id]=(S.vc[id]||0)+1; S.xp+=xp; playSound('pop'); } else { S.vc[id]=Math.max(0,(S.vc[id]||0)-1); S.xp=Math.max(0,S.xp-xp); } S.lv=lvFrom(S.xp); checkLevelUp(oldLv); checkQ(); checkA(); saveState(); markDirty('today'); markDirty('topbar'); markDirty('lv'); markDirty('progress'); renderDynamic(); }
  function toggleD(id) { const de=DEEDS.find(x=>x.id===id); if(!de) return; const l=tlog(); const w=!!l.d[id]; const oldLv=S.lv; l.d[id]=!w; let xp=de.xp; if(S.ab&&S.ab.exp>=today()) xp*=2; if(!w){ S.td[id]=(S.td[id]||0)+1; S.xp+=xp; playSound('pop'); } else { S.td[id]=Math.max(0,(S.td[id]||0)-1); S.xp=Math.max(0,S.xp-xp); } S.lv=lvFrom(S.xp); checkLevelUp(oldLv); recalc(); checkQ(); checkA(); saveState(); markDirty('today'); markDirty('topbar'); markDirty('lv'); markDirty('progress'); renderDynamic(); if (typeof window.autoTrackJourneyProgress === 'function') window.autoTrackJourneyProgress(); }
  function recalc() { const all=Object.keys(S.log).filter(d=>Object.values((S.log[d]&&S.log[d].p)||{}).filter(v=>v).length>=5).sort(); let best=0,run=0,prev=null; for(const d of all){ if(prev){ const p=new Date(prev+'T00:00:00'); const c=new Date(d+'T00:00:00'); const diffDays=Math.round((c-p)/86400000); if(diffDays===1) run++; else run=1; } else { run=1; } best=Math.max(best,run); prev=d; } S.bs=best; const tc=Object.values(tlog().p||{}).filter(v=>v).length>=5; if(tc){ let s=1,ck=new Date(); while(true){ ck.setDate(ck.getDate()-1); const dk=today(ck); if(S.log[dk]&&Object.values(S.log[dk].p||{}).filter(v=>v).length>=5) s++; else break; } S.cs=s; if(typeof checkSurpriseReward==='function') checkSurpriseReward('allPrayers'); } else { const yd=today(new Date(Date.now()-86400000)); S.cs=(S.log[yd]&&Object.values(S.log[yd].p||{}).filter(v=>v).length>=5)?1:0; } S.pd=(S.pdArchived||0)+all.length; if(S.cs>S.bs) S.bs=S.cs; if(window.checkMilestones) checkMilestones(); }
  window.toggleP = toggleP;
  window.toggleV = toggleV;
  window.toggleD = toggleD;
  window.recalc = recalc;
})();
